=== Nedwardo/chummer5a/Chummer/data/drugs.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:include schemaLocation="bonuses.xsd" />
  <xs:include schemaLocation="conditions.xsd" />
  <xs:element name="chummer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="drugs">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="drug" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:string"/>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="category" type="xs:string"/>
                    <xs:element name="rating" type="xs:integer"/>
                    <xs:element name="source" type="xs:string" minOccurs="0"/>
                    <xs:element name="page" type="xs:string" minOccurs="0"/>
                    <xs:element name="avail" type="xs:string" minOccurs="0"/>
                    <xs:element name="cost" type="xs:string" minOccurs="0"/>
                    <xs:element name="speed" type="xs:string" minOccurs="0"/>
                    <xs:element name="vectors" type="xs:string" minOccurs="0"/>
                    <xs:element name="duration" type="xs:string" minOccurs="0"/>
                    <xs:element name="bonus" type="bonusTypes"  minOccurs="0" maxOccurs="1" />
                    <xs:element ref="forbidden" minOccurs="0" maxOccurs="1" />
                    <xs:element ref="required" minOccurs="0" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Nedwardo/chummer5a/Chummer/data/drugs.xml
<?xml version="1.0" encoding="utf-8"?>

<!--This file is part of Chummer5a.

    Chummer5a is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Chummer5a is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Chummer5a.  If not, see <http://www.gnu.org/licenses/>.

    You can obtain the full source code for Chummer5a at
    https://github.com/chummer5a/chummer5a
-->

<chummer xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3.org/2001/XMLSchema drugs.xsd">
  <drugs>
  <!-- Region SR5 -->
  <drug>
    <id>62bffcd7-4a43-45cd-9cf7-3067ba9688f6</id>
    <name>Bliss</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>SR5</source>
    <page>411</page>
    <avail>3F</avail>
    <cost>15</cost>
    <speed>1</speed>
    <vectors>Inhalation,Injection</vectors>
    <duration>(6-{BOD})*3600</duration>
    <bonus>
      <attribute>
        <name>REA</name>
        <value>1</value>
      </attribute>
      <limit>
        <name>Mental</name>
        <value>-1</value>
      </limit>
      <limit>
        <name>Physical</name>
        <value>-1</value>
      </limit>
      <limit>
        <name>Social</name>
        <value>-1</value>
      </limit>
      <quality rating="3">High Pain Tolerance</quality>
    </bonus>
  </drug>
  <drug>
    <id>8dc829b9-8b94-4510-ab1a-2305cbad69c9</id>
    <name>Cram</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>SR5</source>
    <page>411</page>
    <avail>2R</avail>
    <cost>10</cost>
    <speed>600</speed>
    <vectors>Inhalation,Injection</vectors>
    <duration>(12-{BOD})*3600</duration>
    <bonus>
      <attribute>
        <name>REA</name>
        <value>1</value>
      </attribute>
      <initiativedice>1</initiativedice>
    </bonus>
  </drug>
  <drug>
    <id>5f5bc907-ce31-4f34-b7cf-a48d9d5d10b3</id>
    <name>Deepweed</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>SR5</source>
    <page>411</page>
    <avail>8F</avail>
    <cost>400</cost>
    <speed>1</speed>
    <vectors>Inhalation,Injection</vectors>
    <duration>(6-{BOD})*3600</duration>
    <bonus>
      <attribute>
        <name>REA</name>
        <value>1</value>
      </attribute>
      <attribute>
        <name>WIL</name>
        <value>1</value>
      </attribute>
      <limit>
        <name>Physical</name>
        <value>-1</value>
      </limit>
      <limit>
        <name>Mental</name>
        <value>1</value>
      </limit>
      <initiativedice>1</initiativedice>
    </bonus>
  </drug>
  <drug>
    <id>929c4835-1754-4999-9215-9859e8ec5384</id>
    <name>Jazz</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>SR5</source>
    <page>411</page>
    <avail>2R</avail>
    <cost>75</cost>
    <speed>1</speed>
    <vectors>Inhalation</vectors>
    <duration>{D6}*600</duration>
    <bonus>
      <attribute>
        <name>REA</name>
        <value>1</value>
      </attribute>
      <limit>
        <name>Physical</name>
        <value>1</value>
      </limit>
      <initiativedice>2</initiativedice>
    </bonus>
  </drug>
  <drug>
    <id>098bf489-bea9-4f17-b3d9-aead979fdc32</id>
    <name>Kamikaze</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>SR5</source>
    <page>412</page>
    <avail>4R</avail>
    <cost>100</cost>
    <speed>1</speed>
    <vectors>Inhalation</vectors>
    <duration>{D6}*600</duration>
    <bonus>
      <attribute>
        <name>AGI</name>
        <value>1</value>
      </attribute>
      <attribute>
        <name>BOD</name>
        <value>1</value>
      </attribute>
      <attribute>
        <name>REA</name>
        <value>1</value>
      </attribute>
      <attribute>
        <name>STR</name>
        <value>2</value>
      </attribute>
      <attribute>
        <name>WIL</name>
        <value>1</value>
      </attribute>
      <limit>
        <name>Physical</name>
        <value>2</value>
      </limit>
      <initiativedice>2</initiativedice>
      <quality rating="3">High Pain Tolerance</quality>
    </bonus>
  </drug>
  <drug>
    <id>d4cf626d-0af1-41f7-bec0-e53b4dba2eb1</id>
    <name>Long Haul</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>SR5</source>
    <page>412</page>
    <avail>0</avail>
    <cost>50</cost>
    <speed>600</speed>
    <vectors>Injection</vectors>
    <duration>345600</duration>
  </drug>
  <drug>
    <id>d7ec13fa-8601-4f9c-a59c-6a86573b40ee</id>
    <name>Nitro</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>SR5</source>
    <page>412</page>
    <avail>2R</avail>
    <cost>50</cost>
    <speed>6</speed>
    <vectors>Inhalation</vectors>
    <duration>{D6}*600</duration>
    <bonus>
      <attribute>
        <name>STR</name>
        <value>2</value>
      </attribute>
      <attribute>
        <name>WIL</name>
        <value>2</value>
      </attribute>
      <limit>
        <name>Physical</name>
        <value>2</value>
      </limit>
      <specificskill>
        <name>Perception</name>
        <bonus>2</bonus>
      </specificskill>
      <quality rating="6">High Pain Tolerance</quality>
    </bonus>
  </drug>
  <drug>
    <id>836f54d5-1e11-49ea-b115-34c14ed843c9</id>
    <name>Novacoke</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>SR5</source>
    <page>412</page>
    <avail>2R</avail>
    <cost>10</cost>
    <speed>6</speed>
    <vectors>Inhalation,Injection</vectors>
    <duration>(10-{BOD})*3600</duration>
    <bonus>
      <attribute>
        <name>CHA</name>
        <value>1</value>
      </attribute>
      <attribute>
        <name>REA</name>
        <value>1</value>
      </attribute>
      <limit>
        <name>Social</name>
        <value>2</value>
      </limit>
      <quality rating="1">High Pain Tolerance</quality>
      <specificskill>
        <name>Perception</name>
        <bonus>1</bonus>
      </specificskill>
    </bonus>
  </drug>
  <drug>
    <id>778eefae-94ad-4f8c-ad03-8b9039b5c48e</id>
    <name>Psyche</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>SR5</source>
    <page>412</page>
    <avail>0</avail>
    <cost>200</cost>
    <speed>600</speed>
    <vectors>Inhalation,Injection</vectors>
    <duration>(12-{BOD})*3600</duration>
    <bonus>
      <attribute>
        <name>INT</name>
        <value>1</value>
      </attribute>
      <attribute>
        <name>LOG</name>
        <value>1</value>
      </attribute>
      <limit>
        <name>Mental</name>
        <value>1</value>
      </limit>
    </bonus>
  </drug>
  <drug>
    <id>3a946800-be1e-4bbb-899a-c3d1c48a3a31</id>
    <name>Zen</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>SR5</source>
    <page>412</page>
    <avail>4R</avail>
    <cost>5</cost>
    <speed>300</speed>
    <vectors>Inhalation</vectors>
    <duration>{D6}*600</duration>
    <bonus>
      <attribute>
        <name>REA</name>
        <value>-2</value>
      </attribute>
      <attribute>
        <name>WIL</name>
        <value>1</value>
      </attribute>
    </bonus>
  </drug>
  <!-- End Region -->
  <!-- Region Bullets and Bandages-->
  <drug>
    <id>35309aeb-0cbc-4b64-a809-34de50812564</id>
    <name>Crash</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>BB</source>
    <page>19</page>
    <avail>3</avail>
    <cost>800</cost>
  </drug>
  <drug>
    <id>c4ae816f-f683-469d-a7cd-ec1931740e1e</id>
    <name>Cryo</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>BB</source>
    <page>19</page>
    <avail>8R</avail>
    <cost>1000</cost>
  </drug>
  <drug>
    <id>5929d3b9-451b-4be8-a292-8b6509d0aeb9</id>
    <!-- ReSharper disable once MarkupTextTypo -->
    <name>HemoSynth</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>BB</source>
    <page>19</page>
    <avail>4</avail>
    <cost>2000</cost>
  </drug>
  <drug>
    <id>076825cd-dc6f-4e48-8c73-e958b21c1766</id>
    <name>NanoScan</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>BB</source>
    <page>19</page>
    <avail>5</avail>
    <cost>500</cost>
  </drug>
  <drug>
    <id>cf2dd622-8312-4807-97f0-c5d30f9f67b4</id>
    <name>Neostigmine</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>BB</source>
    <page>19</page>
    <avail>2</avail>
    <cost>100</cost>
  </drug>
  <drug>
    <id>1135e850-8371-4827-b2fe-94f5659583d4</id>
    <name>Ondansetron</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>BB</source>
    <page>19</page>
    <avail>2</avail>
    <cost>50</cost>
  </drug>
  <drug>
    <id>b14cc8cf-8d19-4306-a71a-9a7f761eb321</id>
    <name>Sugammadex</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>BB</source>
    <page>19</page>
    <avail>6</avail>
    <cost>100</cost>
  </drug>
  <!-- End Region -->
  <drug>
    <id>1e391e72-1c21-44b3-b935-7abfba2dca43</id>
    <name>Evo Aphrodite Reactive Biomatter</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>TVG</source>
    <page>19</page>
    <avail>8</avail>
    <cost>1000</cost>
  </drug>
  <!-- Region Lockdown -->
  <drug>
    <id>c113d0e8-8720-47fb-9ac6-fdc9e262c94b</id>
    <name>Accelerator</name>
    <category>Drugs</category>
    <rating>0</rating>
    <source>LCD</source>
    <page>205</page>
    <avail>6R</avail>
    <cost>200</cost>
  </drug>
  <drug>
    <id>ee783a4e-331f-4e03-bf47-7ecb93341919</id>
    <name>Buffout</name>
    <category>Drugs</category>
    <rating>0</rating>
